# Generated by Django 4.2.7 on 2026-09-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[("DEMO", "Demo"), ("FULL", "Full")],
                default="DEMO",
                max_length=10,
            ),
        ),
    ]
