import enum


class CreateFlightFailureReason(enum.Enum):
    MISSING_FIELDS = "MISSING_FIELDS"
    INVALID_FLIGHT_NUMBER = "INVALID_FLIGHT_NUMBER"
    INVALID_AIRLINE = "INVALID_AIRLINE"
    INVALID_AIRPORT = "INVALID_AIRPORT"
    INVALID_DATE = "INVALID_DATE"
    ALREADY_REGISTERED = "ALREADY_REGISTERED"
