import enum


class CreateCustomerFailureReason(enum.Enum):
    INVALID_CUSTOMER = "INVALID_CUSTOMER"
    MISSING_FIELDS = "MISSING_FIELDS"
    INVALID_EMAIL = "INVALID_EMAIL"
    ALREADY_REGISTERED = "ALREADY_REGISTERED"


class CreateReservationFailureReason(enum.Enum):
    MISSING_FIELDS = "MISSING_FIELDS"
    OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
    ALREADY_REGISTERED = "ALREADY_REGISTERED"
    VALIDATION_ERROR = "VALIDATION_ERROR"    


class CreateSupplierFailureReason(enum.Enum):
    MISSING_FIELDS = "MISSING_FIELDS"
    ALREADY_REGISTERED = "ALREADY_REGISTERED"


class SupplierFailureReason(enum.Enum):
    INVALID_SUPPLIER = "INVALID_SUPPLIER"
