# Generated by Django 4.2.7 on 2026-06-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "iata",
                    models.CharField(
                        help_text="Ex: LA, G3, etc.", max_length=3, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iata", models.CharField(db_index=True, max_length=3, unique=True)),
                (
                    "icao",
                    models.CharField(blank=True, max_length=4, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=4)),
                ("departure_date", models.DateTimeField(db_index=True)),
                ("arrival_date", models.DateTimeField(blank=True, null=True)),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="flights.airline",
                    ),
                ),
                (
                    "arrival_airport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrivals",
                        to="flights.airport",
                    ),
                ),
                (
                    "departure_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departures",
                        to="flights.airport",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["flight_number", "departure_date"],
                        name="flights_fli_flight__d8926c_idx",
                    )
                ],
                "unique_together": {("flight_number", "airline", "departure_date")},
            },
        ),
    ]
