# Generated by Django 4.2.7 on 2026-06-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="arrival_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arrivals",
                to="flights.airport",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_date",
            field=models.DateTimeField(),
        ),
    ]
