from enum import Enum


class LoginViewFailureReason(Enum):
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_TURNSTILE_TOKEN = "INVALID_TURNSTILE_TOKEN"


class CreateOrUpdateUserFailureReason(Enum):
    MISSING_FIELDS = "MISSING_FIELDS"
    INVALID_ROLE = "INVALID_ROLE"
    ALREADY_REGISTERED = "ALREADY_REGISTERED"
    INVALID_USER = "INVALID_USER"
    INVALID_EMAIL = "INVALID_EMAIL"
