# Generated by Django 4.2.7 on 2026-06-14 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="WhatsApp",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("phone", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("address_number", models.CharField(max_length=100)),
                ("complement", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("b2c", "B2C"), ("b2b", "B2B")], max_length=3
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("money", "Cash"),
                            ("transfer", "Transfer"),
                            ("ticket", "Ticket"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sale_date", models.DateField(db_index=True)),
                ("indication", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agency.customer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locator", models.CharField(max_length=20, unique=True)),
                ("passenger_count", models.PositiveIntegerField()),
                ("passengers", models.TextField(blank=True, null=True)),
                (
                    "flights",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None, related_name="reservations", to="flights.flight"
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agency.sale"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="agency.supplier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
